site_name: Faust Documentation
site_description: A guide to the Faust Programming Language.
copyright: Copyright &copy; 2020-2023 <a href="https://www.grame.fr">Grame-CNCM</a>
nav:
    - Home: index.md 

theme: 
  name: mkdocs
  custom_dir: 'theme'
  navigation_depth: 4

site_dir: ../site

extra:
    social:
        - type: github
          link: https://github.com/grame-cncm/faustdoc
        - type: home
          link: https://faust.grame.fr
        - type: envelope
          link: mailto:research@grame.fr

plugins:
    - search

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - admonition
    - markdown_include.include:
        base_path: './docs'
